server.port: 8088

spring:
    application.name: s4a-task
    output.ansi.enabled: always
    datasource:
        url: jdbc:h2:mem:s4a;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    h2.console:
        enabled: true
        path: /h2-console
        settings:
            web-allow-others: true
    jackson:
        serialization:
            write-dates-with-zone-id: true
        deserialization:
            adjust_dates_to_context_time_zone: false
    jpa.hibernate.ddl-auto: none
